export { cn } from './lib/utils'
export { tokens, type TokenChart, type TokenColor } from './lib/tokens'
export { composeRefs, useComposedRefs } from './lib/compose-refs'

// Hooks
export { useIsomorphicLayoutEffect } from './hooks/use-isomorphic-layout-effect'
export { useAsRef } from './hooks/use-as-ref'
export { useIsMobile } from './hooks/use-mobile'
export { useDataTable } from './hooks/use-data-table'
export type { DataTableState, DataTableStateProps } from './hooks/use-data-table'
export { useDataGrid, type UseDataGridProps } from './hooks/use-data-grid'
export { useDataGridUndoRedo, type UndoRedoCellUpdate } from './hooks/use-data-grid-undo-redo'

// Page primitives
export { PageHeader } from './components/page/page-header'
export { EmptyState } from './components/page/empty-state'
export { ConfirmDialog } from './components/page/confirm-dialog'
export { ErrorState } from './components/page/error-state'
export type { ErrorStateProps } from './components/page/error-state'
export { Toaster } from './components/page/toaster'
export { CardGridSkeleton } from './components/page/card-grid-skeleton'
export { ListSkeleton } from './components/page/list-skeleton'
export { DetailSkeleton } from './components/page/detail-skeleton'

// DataGrid surface
export { DataGrid } from './components/data-grid/data-grid'
export { DataGridCell } from './components/data-grid/data-grid-cell'
export { DataGridCellWrapper } from './components/data-grid/data-grid-cell-wrapper'
export { ShortTextCell, LongTextCell, NumberCell, UrlCell, CheckboxCell, SelectCell, MultiSelectCell, DateCell, FileCell } from './components/data-grid/data-grid-cell-variants'
export { DataGridColumnHeader } from './components/data-grid/data-grid-column-header'
export { DataGridContextMenu } from './components/data-grid/data-grid-context-menu'
export { DataGridFilterMenu } from './components/data-grid/data-grid-filter-menu'
export { DataGridKeyboardShortcuts } from './components/data-grid/data-grid-keyboard-shortcuts'
export { DataGridPasteDialog } from './components/data-grid/data-grid-paste-dialog'
export { DataGridRowHeightMenu } from './components/data-grid/data-grid-row-height-menu'
export { DataGridRow } from './components/data-grid/data-grid-row'
export { DataGridSearch } from './components/data-grid/data-grid-search'
export { getDataGridSelectColumn } from './components/data-grid/data-grid-select-column'
export { DataGridSkeleton, DataGridSkeletonGrid, DataGridSkeletonToolbar } from './components/data-grid/data-grid-skeleton'
export { DataGridSortMenu } from './components/data-grid/data-grid-sort-menu'
export { DataGridViewMenu } from './components/data-grid/data-grid-view-menu'
export { VariantMenu, CELL_VARIANTS } from './components/data-grid/variant-menu'
export type { Direction, RowHeightValue, CellSelectOption, CellOpts, CellUpdate, CellPosition, CellRange, SelectionState, ContextMenuState, PasteDialogState, NavigationDirection, SearchState, DataGridCellProps, FileCellData, TextFilterOperator, NumberFilterOperator, DateFilterOperator, SelectFilterOperator, BooleanFilterOperator, FilterOperator, FilterValue } from './types/data-grid'

// DataTable surface
export { DataTable } from './components/data-table/data-table'
export { DataTableColumnHeader } from './components/data-table/data-table-column-header'
export { DataTableDateFilter } from './components/data-table/data-table-date-filter'
export { DataTableFacetedFilter } from './components/data-table/data-table-faceted-filter'
export { DataTablePagination } from './components/data-table/data-table-pagination'
export { DataTableSkeleton } from './components/data-table/data-table-skeleton'
export { DataTableSliderFilter } from './components/data-table/data-table-slider-filter'
export { DataTableToolbar } from './components/data-table/data-table-toolbar'
export { DataTableViewOptions } from './components/data-table/data-table-view-options'
export type { QueryKeys, Option, FilterVariant, JoinOperator, ExtendedColumnSort, DataTableRowAction } from './types/data-table'
// Note: FilterOperator from types/data-table is intentionally omitted — types/data-grid exports a same-named but different type; consumers import directly from the relevant types file if needed

// Notification hooks (Phase 3)
export { notificationKeys, useNotificationsQueryOptions, useMarkReadMutation, useMarkAllReadMutation } from './hooks/use-notifications'
export { preferenceKeys, useNotificationPreferencesQuery, useUpdateNotificationPreferences } from './hooks/use-notification-preferences'

// Notification surfaces (Phase 3)
export { NotificationItem } from './components/notifications/notification-item'
export type { NotificationItemProps } from './components/notifications/notification-item'
export { NotificationBell } from './components/notifications/notification-bell'
export type { NotificationBellProps } from './components/notifications/notification-bell'
export { NotificationInbox } from './components/notifications/notification-inbox'
export type { NotificationInboxProps } from './components/notifications/notification-inbox'
export { NotificationPreferences } from './components/notifications/notification-preferences'

// Webhook hooks (Phase 3)
export { webhookKeys, useWebhooksQueryOptions, useCreateWebhookMutation, useUpdateWebhookMutation, useDeleteWebhookMutation, useRotateWebhookSecretMutation } from './hooks/use-webhooks'

// Webhook surfaces (Phase 3)
export { WebhookHealthBadge } from './components/webhooks/webhook-health-badge'
export type { WebhookHealthBadgeProps } from './components/webhooks/webhook-health-badge'
export { WebhookList } from './components/webhooks/webhook-list'
export type { WebhookListProps } from './components/webhooks/webhook-list'
export { WebhookSecretReveal } from './components/webhooks/webhook-secret-reveal'
export type { WebhookSecretRevealProps } from './components/webhooks/webhook-secret-reveal'
export { WebhookCreateModal } from './components/webhooks/webhook-create-modal'
export type { WebhookCreateModalProps } from './components/webhooks/webhook-create-modal'
export { WebhookRotateSecretModal } from './components/webhooks/webhook-rotate-secret-modal'
export type { WebhookRotateSecretModalProps } from './components/webhooks/webhook-rotate-secret-modal'
export { EventTypesInput } from './components/webhooks/event-types-input'
export type { EventTypesInputProps } from './components/webhooks/event-types-input'

// Provider & adapter seam (Phase 3)
export { FarsightProvider, useFarsightContext, FarsightContext } from './provider/farsight-provider'
export type { FarsightProviderProps, TenantContext, FarsightContextValue } from './provider/farsight-provider'
export { useTenant } from './provider/use-tenant'
export { useApiClient } from './provider/use-api-client'
export { createApiClient, ApiClientError, ApiClientSchemaError } from './client/create-client'
export type { ApiClient, CreateApiClientOptions } from './client/create-client'
export { toFarsightError, isFarsightError, matchCode } from './errors/farsight-error'
export type { FarsightError, FarsightSchemaError } from './errors/farsight-error'

// Dataset hooks (Phase 4)
export { datasetKeys, useDatasetsQueryOptions, useDatasetQueryOptions, useDatasetRecordsQueryOptions, useDeleteDatasetMutation, useSearchDatasetMutation } from './hooks/use-datasets'

// Dataset surfaces (Phase 4)
export { DatasetList } from './components/datasets/dataset-list'
export type { DatasetListProps } from './components/datasets/dataset-list'
export { DatasetDetail } from './components/datasets/dataset-detail'
export type { DatasetDetailProps } from './components/datasets/dataset-detail'
export { DatasetRecords } from './components/datasets/dataset-records'
export { DatasetSearch } from './components/datasets/dataset-search'

// Workflow (pipeline) hooks (Phase 4)
export { workflowKeys, useWorkflowsQueryOptions, useWorkflowQueryOptions, useCreateWorkflowMutation, useUpdateWorkflowMutation, useRunWorkflowMutation, useDeleteWorkflowMutation } from './hooks/use-workflows'

// Workflow (pipeline) surfaces (Phase 4)
export { WorkflowList } from './components/pipelines/workflow-list'
export type { WorkflowListProps } from './components/pipelines/workflow-list'
export { WorkflowCanvas } from './components/pipelines/workflow-canvas'
export type { WorkflowCanvasProps } from './components/pipelines/workflow-canvas'
export { WorkflowRunView } from './components/pipelines/workflow-run-view'
export type { WorkflowRunViewProps } from './components/pipelines/workflow-run-view'
export { SourceNode } from './components/pipelines/nodes/source-node'
export { TransformNode } from './components/pipelines/nodes/transform-node'
export { SinkNode } from './components/pipelines/nodes/sink-node'
export { toFlowNode, toDefinition, validatePipelineGraph } from './components/pipelines/pipeline-adapter'
export { NODE_IDS, nodeTypeFor } from './components/pipelines/node-ids'
export type { NodeIdKey } from './components/pipelines/node-ids'

// Canvas-kit (Phase 4)
export { CanvasFlow } from './components/canvas-kit/canvas-flow'
export type { CanvasFlowProps } from './components/canvas-kit/canvas-flow'
export { CanvasBackground } from './components/canvas-kit/canvas-background'
export { CanvasControls } from './components/canvas-kit/canvas-controls'
export { CanvasMiniMap } from './components/canvas-kit/canvas-minimap'
export { CanvasPanel } from './components/canvas-kit/canvas-panel'
export type { CanvasPanelProps } from './components/canvas-kit/canvas-panel'
export { CanvasInspector } from './components/canvas-kit/canvas-inspector'
export type { CanvasInspectorProps } from './components/canvas-kit/canvas-inspector'
export { CanvasPalette } from './components/canvas-kit/canvas-palette'
export type { CanvasPaletteProps, PaletteItem } from './components/canvas-kit/canvas-palette'
export { autoLayout } from './components/canvas-kit/auto-layout'

// UI primitives
export { Button, buttonVariants } from './components/ui/button'
export { Label } from './components/ui/label'
export { ActionBar, ActionBarSelection, ActionBarGroup, ActionBarItem, ActionBarClose, ActionBarSeparator } from './components/ui/action-bar'
export type { ActionBarProps } from './components/ui/action-bar'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger } from './components/ui/alert-dialog'
export { Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup, AvatarGroupCount } from './components/ui/avatar'
export { Badge, badgeVariants } from './components/ui/badge'
export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis } from './components/ui/breadcrumb'
export { Calendar, CalendarDayButton } from './components/ui/calendar'
export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent } from './components/ui/card'
export { ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent, ChartStyle } from './components/ui/chart'
export type { ChartConfig } from './components/ui/chart'
export { Checkbox } from './components/ui/checkbox'
export { Collapsible, CollapsibleTrigger, CollapsibleContent } from './components/ui/collapsible'
export { Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandShortcut, CommandSeparator } from './components/ui/command'
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger } from './components/ui/dialog'
export { DropdownMenu, DropdownMenuPortal, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuLabel, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent } from './components/ui/dropdown-menu'
export { GridPattern } from './components/ui/grid-pattern'
export type { GridPatternProps } from './components/ui/grid-pattern'
export { Input } from './components/ui/input'
export { Kbd, KbdGroup } from './components/ui/kbd'
export { Popover, PopoverTrigger, PopoverContent, PopoverAnchor, PopoverHeader, PopoverTitle, PopoverDescription } from './components/ui/popover'
export { Progress } from './components/ui/progress'
export { RadioGroup, RadioGroupItem } from './components/ui/radio-group'
export { ScrollArea, ScrollBar } from './components/ui/scroll-area'
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue } from './components/ui/select'
export { Separator } from './components/ui/separator'
export { Sheet, SheetTrigger, SheetClose, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription } from './components/ui/sheet'
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar } from './components/ui/sidebar'
export { Skeleton } from './components/ui/skeleton'
export { Slider } from './components/ui/slider'
export { Sortable, SortableContent, SortableItem, SortableItemHandle, SortableOverlay, Root, Content, Item, ItemHandle, Overlay } from './components/ui/sortable'
export { Switch } from './components/ui/switch'
export { Table, TableHeader, TableBody, TableFooter, TableHead, TableRow, TableCell, TableCaption } from './components/ui/table'
export { Tabs, TabsList, TabsTrigger, TabsContent, tabsListVariants } from './components/ui/tabs'
export { Textarea } from './components/ui/textarea'
export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from './components/ui/tooltip'
